"""adding is_paid column to ticket model

Revision ID: 257bf8263205
Revises: 805ba0a96d28
Create Date: 2023-04-02 11:29:24.866554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257bf8263205'
down_revision = '805ba0a96d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tickets', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ticket', ['tickets'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tickets')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
