"""added screen time to movie model

Revision ID: 313755ee9335
Revises: 191b661d40d7
Create Date: 2023-04-10 13:12:43.501120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313755ee9335'
down_revision = '191b661d40d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screen_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('screen_time')

    # ### end Alembic commands ###
