"""changed stripe_account field in models to not nullable

Revision ID: 32981bb22597
Revises: 5fb14661b69e
Create Date: 2023-04-15 10:39:01.579329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32981bb22597'
down_revision = '5fb14661b69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('stripe_account',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('stripe_account',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
