"""replacing card_number field with wise_account

Revision ID: 396922404de5
Revises: cae0c561e4ae
Create Date: 2023-04-03 13:07:04.602795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396922404de5'
down_revision = 'cae0c561e4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wise_account', sa.String(), nullable=True))
        batch_op.drop_column('card_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('wise_account')

    # ### end Alembic commands ###
