"""forgot to name the transaction model

Revision ID: 45e40a396897
Revises: 11e7011a9e69
Create Date: 2023-04-06 13:39:49.813079

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "45e40a396897"
down_revision = "11e7011a9e69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("transaction")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ticket_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("payment_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["ticket.id"], name="transaction_ticket_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="transaction_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="transaction_pkey"),
    )
    op.drop_table("transactions")
    # ### end Alembic commands ###
