"""switched ticket_price from one model to another

Revision ID: 4aed91b70393
Revises: 3b7e1a1731e2
Create Date: 2023-04-03 17:49:14.369805

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4aed91b70393"
down_revision = "3b7e1a1731e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movie", schema=None) as batch_op:
        batch_op.drop_column("ticket_price")

    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ticket_price", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ticket", schema=None) as batch_op:
        batch_op.drop_column("ticket_price")

    with op.batch_alter_table("movie", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ticket_price",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
