"""changed the model name table

Revision ID: 58c0381d2a85
Revises: 8ce914449158
Create Date: 2023-04-13 11:17:48.517901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "58c0381d2a85"
down_revision = "8ce914449158"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hall_availability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hall_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hall_id"],
            ["hall.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("HallAvailability")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "HallAvailability",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"HallAvailability_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("hall_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "start_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["hall_id"], ["hall.id"], name="HallAvailability_hall_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="HallAvailability_pkey"),
    )
    op.drop_table("hall_availability")
    # ### end Alembic commands ###
