"""added movie it to hall availability

Revision ID: 5fb14661b69e
Revises: 58c0381d2a85
Create Date: 2023-04-13 11:21:06.904657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb14661b69e'
down_revision = '58c0381d2a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall_availability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
