"""adding unique username

Revision ID: 945b5df45faf
Revises: 5719d38ba838
Create Date: 2023-04-06 10:35:18.159653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945b5df45faf'
down_revision = '5719d38ba838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
