"""creating movie model

Revision ID: b9877f18aa4e
Revises: d982343dee1b
Create Date: 2023-03-30 11:58:57.713533

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b9877f18aa4e"
down_revision = "d982343dee1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie")
    # ### end Alembic commands ###
