"""removing the tickets fields

Revision ID: cae0c561e4ae
Revises: 257bf8263205
Create Date: 2023-04-02 11:31:42.628954

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "cae0c561e4ae"
down_revision = "257bf8263205"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("user_tickets_fkey", type_="foreignkey")
        batch_op.drop_column("tickets")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tickets", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key("user_tickets_fkey", "ticket", ["tickets"], ["id"])

    # ### end Alembic commands ###
