"""creating hall model and making relation with movies

Revision ID: ece6bfd4755d
Revises: b9877f18aa4e
Create Date: 2023-03-30 12:04:09.187849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece6bfd4755d'
down_revision = 'b9877f18aa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hall_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'hall', ['hall_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hall_id')

    op.drop_table('hall')
    # ### end Alembic commands ###
